spring.application.name=machinemonitorsystem

#database related config
spring.datasource.url=jdbc:mysql://localhost:3306/kir_server_db?serverTimezone=UTC
spring.datasource.username=linemachine
spring.datasource.password=1234fast
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#CORS related config
cors.allowed-origins=http://localhost:4200,http://localhost:8180

##Logger related configuration
logging.level.root=info
logging.file.name=./logs/MachineMonitoringSystem.log