spring.application.name=machinemonitorsystem

#database related config

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# the following is for JNDI-which is not used for local running but for JBoss server
# so, if run application locally in IntelliJ, comment this line
# if build war package for JBoss via `mvn clean install`, need to keep this line
spring.datasource.jndi-name=java:jboss/datasources/MySqlDS

#CORS related config
cors.allowed-origins=http://localhost:4200,http://localhost:8180

#logging.level.org.apache.catalina=DEBUG
#logging.level.org.hibernate=DEBUG
# recently  use the following two
#logging.level.org.springframework=DEBUG
#logging.level.root=DEBUG