spring.application.name=machinemonitorsystem

#this is to supress the Unable to start web server Caused by: java.lang.IllegalStateException when deploying to JBoss
#comment it when run on local IntelliJ
spring.main.web-application-type=servlet

#this is to solve 'filter errorPageFilterRegistration' when deploying to WildFly
server.servlet.register-beans=false

spring.profiles.active=dev