spring.application.name=machinemonitorsystem

#this is to supress the Unable to start web server Caused by: java.lang.IllegalStateException when deploying to JBoss
#comment it when run on local IntelliJ
spring.main.web-application-type=servlet

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

# Standard SMTP properties for TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

# Corrected timeouts to 10 seconds (10000 milliseconds)
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

#Email Receivers(for simplicity, can be loaded from DB/config server)
app.alert.recipients=jonathanwq.wang@gmail.com

#Scheduling related configuration
#scheduled 60 seconds(1 minute) to monitor the failed product amount
app.scheduling.monitorFailedProduct.fixedRate=60000
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.boot.autoconfigure.mail=DEBUG
logging.level.com.sun.mail=

#this is to guarantee GlobalExceptionHandle catch a NoHandlerFoundException when url has typo
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false


